# Generated by Django 4.2.3 on 2023-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link_H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь Запрос-Отель',
            },
        ),
        migrations.CreateModel(
            name='Link_U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь Запрос-Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=19, unique=True, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщения')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(default='start', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
