# Generated by Django 4.2.3 on 2023-07-08 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='hservice', to='hotel.hservice', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='himg',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_img', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hboost',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_boost', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='groupbooking',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='rservice', to='hotel.booking'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='rc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rcategory'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcomment', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbooking', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubooking', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='booking',
            name='children_ages',
            field=models.ManyToManyField(blank=True, null=True, related_name='ages_c_booking', to='user.child', verbose_name='Возраст детей'),
        ),
        migrations.AddField(
            model_name='booking',
            name='companions',
            field=models.ManyToManyField(blank=True, null=True, related_name='companions_booking', to='user.companion'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='address',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adrress_hotel', to='hotel.hotel'),
        ),
    ]
