# Generated by Django 4.1.3 on 2023-12-03 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='matching_photos',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='quality_of_service',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='rc',
        ),
        migrations.AddField(
            model_name='bonus',
            name='lifespan',
            field=models.PositiveIntegerField(default=182),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='hygiene_products',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='number_quality',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='price_quality_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='rc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel.rcategory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='what_is_bad_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='what_is_good_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='wifi_quality',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='favourite',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hservice',
            name='icon',
            field=models.FileField(default=0, upload_to='img/icon/hservice/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rcategory',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. параметры'),
        ),
        migrations.AddField(
            model_name='rservice',
            name='icon',
            field=models.FileField(default=0, upload_to='img/icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='purity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type_hotel',
            field=models.CharField(choices=[('apart-hotel', 'Апарт-отель'), ('apartments', 'Апартамент'), ('flat', 'Квартира'), ('recreation center', 'База отдыха'), ('hotel_1', 'Гостиница'), ('bungalow', 'Бунгало'), ('boutique hotel', 'Бутик-отель'), ('villa', 'Вилла'), ('glamping', 'Глэмпинг'), ('guest house', 'Гостевой дом'), ('residential premises', 'Жилое помещение'), ('castle', 'Замок'), ('camping', 'Кемпинг'), ('resort hotel', 'Курортный отель'), ('furnished rooms', 'Меблированные комнаты'), ('mini-hotel', 'Мини-отель'), ('bed and breakfast (b&b)', 'Ночлег и завтрак (B&B)'), ('hotel', 'Отель'), ('sanatorium', 'Санаторий'), ('farm', 'Ферма'), ('hostel', 'Хостел'), ('private house', 'Частный дом'), ('chalet', 'Шале')], default='hotel', max_length=450, verbose_name='Тип отеля'),
        ),
        migrations.AlterField(
            model_name='rcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rcategory',
            name='offer_type',
            field=models.CharField(choices=[('number', 'Номер'), ('place_in_the_room', 'Место в номере'), ('atelier', 'Студия'), ('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('house', 'Дом'), ('cottage', 'Коттедж'), ('villa', 'Вилла'), ('separate_room', 'Отдельная комната')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.rcategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ModerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField(blank=True, default=dict, verbose_name='Контактные данные')),
                ('notes', models.JSONField(blank=True, default=dict, verbose_name='Коментарии')),
                ('reminders', models.JSONField(blank=True, default=dict, verbose_name='Напоминания')),
                ('status', models.JSONField(blank=True, default=dict, verbose_name='Статусы')),
                ('param', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('hotels', models.ManyToManyField(null=True, related_name='moderworks', to='hotel.hotel', verbose_name='Отели')),
                ('moder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderworks', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderwork', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
