# Generated by Django 4.1.3 on 2023-12-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_comment_data_remove_comment_matching_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_number_people',
            name='rc',
        ),
        migrations.RemoveField(
            model_name='rimg',
            name='rcategory',
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'Бонус отеля', 'verbose_name_plural': 'Бонусы отеля'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избраные отели'},
        ),
        migrations.AlterModelOptions(
            name='groupbooking',
            options={'verbose_name': 'Группа бронирований', 'verbose_name_plural': 'Группы бронирований'},
        ),
        migrations.DeleteModel(
            name='HImg',
        ),
        migrations.DeleteModel(
            name='Price_number_people',
        ),
        migrations.DeleteModel(
            name='RImg',
        ),
    ]
