# Generated by Django 4.1.3 on 2023-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_bonus_rubles_notification_marks'),
        ('hotel', '0004_remove_price_number_people_rc_remove_rimg_rcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='notification_marks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children_ages',
            field=models.ManyToManyField(blank=True, related_name='ages_c_booking', to='user.child', verbose_name='Возраст детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='companions',
            field=models.ManyToManyField(blank=True, related_name='companions_booking', to='user.companion'),
        ),
        migrations.AlterField(
            model_name='moderwork',
            name='hotels',
            field=models.ManyToManyField(related_name='moderworks', to='hotel.hotel', verbose_name='Отели'),
        ),
    ]
