# Generated by Django 4.1.3 on 2023-12-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_rubles',
            name='lifespan',
            field=models.PositiveIntegerField(default=182),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('param', models.JSONField(blank=True, default=dict)),
                ('push', models.CharField(choices=[('not_shown', 'Не показывать'), ('not_viewed', 'Ещё не показано'), ('shown', 'Показано')], max_length=20)),
                ('view_type', models.CharField(choices=[('not_viewed', 'Ещё не показано'), ('shown', 'Показано'), ('visited', 'Перешёл')], max_length=20)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
