# Generated by Django 4.1.3 on 2023-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_notice_action_notice_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='url',
            field=models.TextField(blank=True, default='/', null=True, verbose_name='Url'),
        ),
    ]
