# Generated by Django 4.1.3 on 2023-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_notice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_rubles',
            name='notification_marks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
