# Generated by Django 4.1.3 on 2023-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('log_type', models.CharField(choices=[('hotel', 'Отель'), ('user', 'Пользователь'), ('site', 'Сайт'), ('api', 'API')], max_length=20)),
            ],
        ),
    ]
