# Generated by Django 4.1.3 on 2023-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_constant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=16)),
                ('orderID', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('param', models.JSONField(default=dict)),
            ],
        ),
    ]
