# Generated by Django 4.1.3 on 2023-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Адрес электронной почты')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
