# Generated by Django 4.1.3 on 2023-12-03 10:59

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_comment_data_remove_comment_matching_photos_and_more'),
        ('utils', '0006_place_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.models.upload_to_path_doc)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('param', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='place',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='places', to='hotel.hotel', verbose_name='Отели'),
        ),
        migrations.AlterField(
            model_name='img',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models.upload_to_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='img',
            name='param',
            field=models.JSONField(default=dict, verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='img',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
