# Generated by Django 4.1.3 on 2023-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_doc_alter_img_options_place_hotels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.JSONField(default=dict)),
            ],
        ),
    ]
