# Generated by Django 4.1.3 on 2023-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='option',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
