# Generated by Django 4.1.3 on 2023-12-23 10:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_documentationpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'verbose_name': 'Лог админа', 'verbose_name_plural': 'Логи админа'},
        ),
        migrations.AlterModelOptions(
            name='constant',
            options={'verbose_name': 'Переменая', 'verbose_name_plural': 'Переменые'},
        ),
        migrations.AlterModelOptions(
            name='documentationpage',
            options={'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='shortlink',
            options={'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='utils.documentationpage', verbose_name='Родительская страница'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='related_pages',
            field=models.ManyToManyField(blank=True, related_name='related', to='utils.documentationpage', verbose_name='Связанные страницы'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
