# Generated by Django 4.1.3 on 2023-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнер',
            },
        ),
    ]
