# Generated by Django 4.1.3 on 2023-12-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('cashback', models.FloatField(verbose_name='Кешбек')),
                ('code', models.CharField(max_length=255, verbose_name='Промокод')),
                ('promo_code_term', models.DateField(blank=True, null=True, verbose_name='Срок промокода')),
                ('number_of_uses', models.IntegerField(blank=True, null=True, verbose_name='Количество использований')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocedes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокод',
            },
        ),
    ]
