# Generated by Django 4.1.3 on 2023-12-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0003_alter_partner_owner_alter_promocode_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partner.partner', verbose_name='Пригласивший партнер'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocedes', to='partner.partner', verbose_name='Партнер'),
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='partner.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
            },
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='partner.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Партнерская ссылка',
                'verbose_name_plural': 'Партнерские ссылки',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='partner.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
