# Generated by Django 4.1.3 on 2023-12-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_invited_by_alter_partner_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='number_of_uses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='title',
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='partner.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Партнерская ссылка',
                'verbose_name_plural': 'Партнерские ссылки',
            },
        ),
    ]
