# Generated by Django 4.1.3 on 2023-12-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_promocode_hotel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Рефарал', 'verbose_name_plural': 'Рефералы'},
        ),
    ]
