# Generated by Django 4.1.3 on 2023-12-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_referral_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Флаг удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='partner.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Партнерская ссылка',
                'verbose_name_plural': 'Партнерские ссылки',
            },
        ),
    ]
