# Generated by Django 4.1.3 on 2023-12-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocedes', to='partner.channel', verbose_name='Канал'),
        ),
    ]
