# Generated by Django 4.1.3 on 2023-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_promocode_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал продаж', 'verbose_name_plural': 'Каналы продаж'},
        ),
        migrations.AddField(
            model_name='partner',
            name='api_key',
            field=models.CharField(default='xY37P9fT5z', max_length=255, verbose_name='API ключ'),
            preserve_default=False,
        ),
    ]
